name: Introduktion till programmering

description: Introduktion till programmering för IA

author:
    name: Anton Tibblin

url: http://da354a.ia-mau.se

highlighter: pygments

markdown: kramdown

exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'vendor']

include: ['.htaccess']

permalink: /blog/:title.html
